### ISSUE TITLE
Circular dependencies with doit and doit-py

### ISSUE THREAD

**Issue by dvzrv** [schettino72/configclass#4]
Hi! When trying to update the python-doit package for Arch Linux I ran into a circular dependency with this package and doit-py.
configclass requires doit and doit-py for testing, while doit-py requires doit and configclass as runtime dependencies and doit now requires doit-py for testing.

For bootstrapping purposes this is very suboptimal. Is there no way to test configclass without doit and doit-py?

**Comment by hartwork** [comment]
Hi David,

nice to meet you. I agree that circular dependencies are not ideal. From a closer look, my impression is that configclass tests can be run with plain pytest, i.e. doit is not a hard dependency of the tests in practice. The configclass package in Gentoo depends on pytest for testing, calls pytest rather than doit, and seems to be fine. Would that approach work for Arch as well?

Best, Sebastian

**Comment by dvzrv** [comment]
@hartwork thanks for the follow up! Yes, I guess that would work as well, if doit is indeed not called from within the tests.
I'll look into this.
All in all I guess splitting the requirements for testing and development could be beneficial here.

**Comment by hartwork** [comment]
`setup.py` doesn't pull in any of these so I don't have any real opinion myself with regard to that change. @schettino72 what do you think about a split like that? @dvzrv would you be up for a PR, in general?

**Comment by dvzrv** [comment]
Sure, but I have still many outstanding packages to bump. Holiday time is "packaging piles up" time :D

I guess a test-requirements.txt and a dev-requirements.txt would be the way to go.

The tests for configclass also work fine with only pytest btw. so closing this.
